---
- hosts: all
  tasks:

      - name: Install zabbix agent
        become: yes
        yum:
            name: zabbix-agent
            state: latest

      - name: Stop service zabbix-agent
        become: yes
        service:
            name: zabbix-agent
            state: stopped

      - name: Remove zabbix config file
        become: yes
        file:
            path: /etc/zabbix/zabbix_agentd.conf
            state: absent

      - name: Create new zabbix config file from template
        become: yes
        template:
            src: "templates/zabbix_agentd.conf.j2"
            dest: "/etc/zabbix/zabbix_agentd.conf"

      - name: Start service zabbix-agent
        become: yes
        service:
            name: zabbix-agent
            state: started
